version: '3'

services:
  app:
    build: .
    command: bash -c "pipenv install --system && python main.py"
    environment:
      FLASK_APP: main
    ports:
      - 5000:5000
    volumes:
      - .:/app
